### ISSUE TITLE
Different HIPIMSs ?

### ISSUE THREAD

**Issue by ninnghazad** [HEMLab/hipims#1]
Hello HEMLab Team!
How does this incarnation of hipims relate to https://github.com/lukessmith/hipims-ocl ? 
I see some of the same authors are involved in both projects. 
I have used smith's version of hipims a lot and recently also tried this version of hipims. 
Both versions seem to have different pros and cons to them, and rather different styles of coding and architecture.
Was there a special reason to start two projects? 
Is one considered to be the "true" or official hipims - seeing how both projects seem to involve authors of the papers regarding hipims?

**Comment by xiaxilin** [comment]
Hi,

hipims-ocl (Smith [2018]) and hipims-cuda (Xia [2017]) originated from two different PhD projects, which were both supervised by Prof Qiuhua Liang. hipims-ocl was focusing on cross-platform compatibility while hipims-cuda was trying to allow relatively easy implementation of different solvers but can only run on cuda devices. As a result, hipims-cuda can also simulate landslide movement quite robustly. There are also other developments such as drainage network and sediment transport. Both hipims-ocl and hipims-cuda have been intensively tested. I would say both versions are 'official', you can have peace of mind when using either of them.

References: 

Smith LS (2018) Computational methods for and applications of high-performance computing in flood simulation, Newcastle University, PhD Thesis.

Xia X (2017) High-performance simulation technologies for water-related natural hazards, Newcastle University, PhD Thesis
