### ISSUE TITLE
ERROR Compiling the source code

### ISSUE THREAD

**Issue by sukimmin** [HEMLab/hipims#2]
Dear Dr. Ming, Dr. Xia and HEMLab members,

I am really interested in your powerful numerical model for large-scale flood simulation by solving 2D- shallow water equations. I have read your publications about the application of the HIPIMS model. So, I would like to test this model and apply this model to my case study by starting from compiling the source code. I have followed the 8 steps that you wrote in the **Userguide.md** for compiling and running the model.  Unfortunately, I have received serval errors while compiling the code using my Windows machine equipped with NVIDIA GPU. So, the folder **'release/bin'** was created during the compiling; however, there are no executable files were created in this folder.

Honestly, I am quite new to parallel computing with CUDA Toolkit. Therefore, I would like to ask for your help to fix this problem in compiling the source code. If you have some time, please kindly check the attached screenshot showing the errors I got. With your experience, I do believe that you will figure out the cause of this error.

I am looking forward to hearing back from you.
Your help is greatly appreciated.

Yours sincerely,
Sukim

![Error Compiling code](https://user-images.githubusercontent.com/102516863/160386097-290a7657-60bb-4cf7-b16a-61af30670ad3.PNG)

Softwares I have installed on my window machine:
**1) Microsoft visual studio 2019**
**2) CUDA Toolkits 10.2**
**3) CMAKE 3.23**

**Comment by xiaxilin** [comment]
Hi, this could be something to do with your complier settings, for which I don't have enough details to say where the problem is. Have you tried the Python APIs - [Pypims](https://pypims.readthedocs.io/en/latest/)? It is relatively easier to install and use.

**Comment by sukimmin** [comment]
Dear Dr. Xia,

First of all, thank you so much for your quick response. I have tried many times to uninstall and reinstall every software needed for compiling the source code; however, it is still not working. Then, I have tried to install **Pypims** using python APIs following your suggestion. Unfortunately, I still face errors while installing. Please kindly find the attached text file for the error I got (just directly copied from my terminal). 

I do really hope that you might figure out the cause of this error.
Your help would be greatly appreciated, sir.

Yours sincerely,
Sukim

[Error installing Pypims.txt](https://github.com/HEMLab/hipims/files/8395533/Error.installing.Pypims.txt)

**Comment by sukimmin** [comment]
Dear Sir,

I have tried many times with other PC also; however, the same error still occurs. I don't know if I missed some important steps to be able to compile the code. 

I am looking forward to hearing from you sir.

Yours sincerely,
Sukim

**Comment by sukimmin** [comment]
Dear Sir,

I can successfully install the [Pypims](https://pypims.readthedocs.io/en/latest/) in my Linux operating system. However, it still does not work on my window machine. 

By the way, I will close this issue since it works well on my Linux machine.

Yours sincerely,

**Comment by xiaxilin** [comment]
Hi,

The solution for running pypims on Windows is available now. Please check the documentation.

https://pypims.readthedocs.io/en/latest/quickstart.html#installing
